### ISSUE TITLE
[Bug] When Scabbard Tools (NotEnoughAnimations) are enabled, they render outside of the cape

### ISSUE THREAD

**Issue by RaptaG** [tr7zw/WaveyCapes#10]
(Note: Doesn't happen without WaveyCapes)

![2022-02-08_17 32 53](https://user-images.githubusercontent.com/77157639/153020592-6f57faa9-8931-4724-94d7-04517f81460c.png)

**Comment by tr7zw** [comment]
Not a bug of WaveyCapes, these tools were a test feature that never was completed and probably will be removed again since there are other mods for this that do it better. Just disable the back item feature in the settings.
