### ISSUE TITLE
Cape Movement > "Simulation" physics is weird

### ISSUE THREAD

**Issue by Scarlaid** [tr7zw/WaveyCapes#15]
How to reproduce:
- Install the mod
- Go to Cape Movement > Simulation 
- ~Jump off a building~ Let the player fall down while in F5 (Freelook for better view)
- While falling, the cape now define a new "gravity definition" 

##### Video to show the movement: https://streamable.com/p2d5jv
![image](https://user-images.githubusercontent.com/90851437/159691467-fede3099-5cd9-4aa5-b6a8-e60b2d7713b3.png)

**Comment by tr7zw** [comment]
There is nothing wrong in that video? You have enabled that the cape has waves in it the entire time, so it has waves in it while falling too.

**Comment by Scarlaid** [comment]
> There is nothing wrong in that video? You have enabled that the cape has waves in it the entire time, so it has waves in it while falling too.

What I'm stating isn't about the wavy cape, it's the "Simulaton", the cape having weird physics with this option, when falling down it just clipping through the playerhead

**Comment by Scarlaid** [comment]
Even turning that wavy cape off, the cape still seems to clip

**Comment by tr7zw** [comment]
Oh that. The cape "simulation" is a reaaaally basic "stick simulation" (from https://youtu.be/PGk0rnyTa1U?t=315 ) that basically knows nothing about the outside world. So the cape won't interact with blocks, the player head, other entities etc. (this is also the reason the cape is calculated as a 2d object) There is a reason that a really 100% good physics cape is $10 a month (https://minecraftphysicsmod.com/pro), this is just a hobby developer alternative to this^^. Making the cape react to the arms/head/blocks would take a looooot of time.

**Comment by tr7zw** [comment]
The only input the simulation has is the players relative movement, and the only constraint it has is that it can't flop to the front of the player + a tiny bit of stiffness so it can't fully fold into itself.

**Comment by Scarlaid** [comment]
ah, understood, this is my first time ever seen this "simulation", kinda misunderstanding it as "bug". 👀

**Comment by tr7zw** [comment]
Personally, I fully expected this issue to be about the only "real bug" where I'm currently still stuck on how to handle it correctly, that is getting the cape over your head like this, and then moving backward. The cape is not allowed to overrotate to get in front of the camera, due to the stiffness it can't just fall down into itself, so it does stay up and glitches around a bit. No clue how to handle that yet.
