### ISSUE TITLE
JMX causes visual issues

### ISSUE THREAD

**Issue by Cccc-owo** [tr7zw/WaveyCapes#20]
After testing, I found that with both [JMX](https://modrinth.com/mod/imx/version/fabric-mc119-1.22.251) and WaveyCapes on,the cape cannot render properly.
This is a gif showing the problem:
<https://cccc-drive.vercel.app/TEMP/2.gif>

**Comment by tr7zw** [comment]
Hm thats the same visual issue Optifine causes(the reason smooth cape is disabled when optifine is installed). No clue why this happens or how to fix it.

**Comment by tr7zw** [comment]
The optifine issue was fixed some time ago, which was a technically illegal usage of the pose stack captures. It should also be fixed here then, reopen the issue if it's still broken.
