### ISSUE TITLE
Compat: Ears is unaffected

### ISSUE THREAD

**Issue by hibiii** [tr7zw/WaveyCapes#21]
Title says it all. Capes decoded from [unascribed/Ears](/unascribed/Ears) capable skins are not affected by Wavey Capes. Easy way out is to call it quits and mark it as incompatible, because as far as I understand from it, it uses its own feature renderer that then calls a delegate. It's a multi-version multi-loader thing of beauty.

**Comment by tr7zw** [comment]
Wait, why does that mod even do anything with Capes?!?
