### ISSUE TITLE
[1.19] Forge breaking changes

### ISSUE THREAD

**Issue by Baggytrousers27** [tr7zw/WaveyCapes#24]
Forges 41.0.64+ and 41.0.94+ introduce breaking changes for waveycapes-forge-1.2.0-mc1.19.

**Comment by tr7zw** [comment]
Like mentioned on my other mods, won't update forge 1.19 till they are done breaking stuff. Use an older forge version or switch to fabric.

**Comment by Baggytrousers27** [comment]
Fair enough. Get done fixing one thing and then they dump 5 more on you.
