### ISSUE TITLE
Incompatible with Optifine (≥1.18)

### ISSUE THREAD

**Issue by Noryea** [tr7zw/WaveyCapes#25]
Capes looks weird with Optifine.
![2022-07-22_11 53 32](https://user-images.githubusercontent.com/88097529/180359056-809ad9ba-ccd4-4167-92af-db4f9fd7bf85.png)
.

**Comment by tr7zw** [comment]
That's intended as noted on the project page. Optifine doesn't work correctly, so only the blocky capes are supported. Consider switching to the more modern Sodium instead.
