### ISSUE TITLE
[compatibility] More Banner Features

### ISSUE THREAD

**Issue by SylisMC** [tr7zw/WaveyCapes#3]
More Banner Features just added a feature to use banners as capes, with trinket integration, these two mods "work" together but WC doesn't make them sexy af 
https://www.curseforge.com/minecraft/mc-mods/more-banner-features

**Comment by tr7zw** [comment]
The mod seems to apply the capes using a custom renderer, therefor not using the vanilla cape. Thats why they dont work together https://github.com/KxmischesDomi/MoreBannerFeatures/blob/2a89b0c062946fe4c3f568bba32deaffdbbba06d/src/main/java/de/kxmischesdomi/morebannerfeatures/client/feature/BannerCapeFeatureRenderer.java#L38

**Comment by tr7zw** [comment]
Looking a bit more into it, the probably best thing to do would be to precompile the banner texture into a normal texture and just bind that to the normal cape/shield, instead of redrawing each layer of the banner/shield.

**Comment by SylisMC** [comment]
You got to that fast, haha nice to see your pride in workmanship. I hope you can find an easy solution!

**Comment by tr7zw** [comment]
Decided to start adding direct support into this mod. Currently just need to fix the UV's.

**Comment by SylisMC** [comment]
You're awesome

**Comment by tr7zw** [comment]
![grafik](https://user-images.githubusercontent.com/5133936/131754054-05c62c7b-aebe-45ff-8c9a-a07e60b7b76e.png)
close

**Comment by tr7zw** [comment]
![grafik](https://user-images.githubusercontent.com/5133936/131754544-406884f2-764b-4cfb-82dc-460831c4dea6.png)
I thiiiink this is correct?

**Comment by SylisMC** [comment]
That looks about right.

**Comment by tr7zw** [comment]
Please give it a try with this build once its done https://github.com/tr7zw/WaveyCapes/actions/runs/1192080841

**Comment by SylisMC** [comment]
im not 100% sure how to tell if thats done, i dont see a download

**Comment by tr7zw** [comment]
The "Artifacts" button at the bottom.

**Comment by SylisMC** [comment]
Ohh, i see, I downloaded that, but it was labeled v1.0.1 so i assumed that was the current, not patched version, haha
Works mint for me

**Comment by SylisMC** [comment]
i dont think you do, i was using the cape in the trinkets slot no problem

**Comment by tr7zw** [comment]
The cape yea, but I think there is an issue if you have a vanilla cape and then use the elytra via the trinket slot.

**Comment by SylisMC** [comment]
Point... good thinking. Let me see if i can break this for you :)

**Comment by SylisMC** [comment]
Cape + Elytra = Fine
![image](https://user-images.githubusercontent.com/19602662/131756790-ec376c20-38c1-4f5e-8da7-c2ce03d64764.png)
![image](https://user-images.githubusercontent.com/19602662/131756819-ff995126-522f-4960-b850-4df302868981.png)

**Comment by tr7zw** [comment]
I think you need a vanilla cape/other mod cape like optifine.

**Comment by tr7zw** [comment]
Having a hard time too replicating it, just managed to crash the game 🙄. Gonna dig into that more tomorrow.
