### ISSUE TITLE
bad rendering on capes

### ISSUE THREAD

**Issue by slovinsqui** [tr7zw/WaveyCapes#32]
the cape design looks cropped for some reason

![image](https://user-images.githubusercontent.com/96891858/202377865-99f8b268-bf79-4a36-a571-14b5796d79cc.png)

maybe it has something to do with More banner features mod (lets you wear banners as capes)
https://www.curseforge.com/minecraft/mc-mods/more-banner-features

**Comment by tr7zw** [comment]
To clarify: it is a known issue with More Banner Features, but currently, the mod is kinda inactive.
