### ISSUE TITLE
Cape's bottom side not rendering at all

### ISSUE THREAD

**Issue by MadeByIToncek** [tr7zw/WaveyCapes#35]
This image shows it all:
[link](https://i.imgur.com/xWbBUnR.png)

**Comment by tr7zw** [comment]
What mc version/mod version are you on?

**Comment by MadeByIToncek** [comment]
waveycapes-fabric-1.2.2-mc1.19.3.jar

**Comment by tr7zw** [comment]
![grafik](https://user-images.githubusercontent.com/5133936/212939779-f788f79b-6c30-4bb2-be6b-067dc3ff711b.png)
Can not reproduce. This is probably not an official cape and has a cut-off texture?

**Comment by MadeByIToncek** [comment]
That could be the case, will test in a second
