### ISSUE TITLE
1.19.2?

### ISSUE THREAD

**Issue by Aces-and-Jacks** [tr7zw/WaveyCapes#36]
I was just wondering if you still plan to support 1.19.2 or dropping in favor of 1.19.3?

**Comment by Aces-and-Jacks** [comment]
by support I mean any features or changes made for 1.19.3 would also eventually be on 1.19.2

**Comment by tr7zw** [comment]
Somewhat. Each added version doubles the workload. I want to try to create a framework for myself, that would make it a lot simpler to maintain multiple old versions, but for now, this isn't made yet. I'll see how well the changes can be backported to 1.19.2, and depend on that. Also note that 1.19.4 is currently in the works, so 1.19.2 physically can't be supported long-term(same reason 1.16.2 or so doesn't get updates).

**Comment by tr7zw** [comment]
Except for a small hickup, I guess it worked fine.
