### ISSUE TITLE
Reduce icon size

### ISSUE THREAD

**Issue by Leva25se** [tr7zw/WaveyCapes#44]
Hello
I think the size of the mod icon should be reduced or the mod icon should be replaced. In mod icon takes up about 79.17% of the binary file size.

mod version: fabric-1.4.0-mc1.20

**Comment by tr7zw** [comment]
I mean, on one hand yea. On the other hand why? The mod has no other textures and images are a lot bigger than text/code. Also, why does the file size at this scale even matter? No one will have an issue downloading or storing a 1mb file.

**Comment by tr7zw** [comment]
Gonna close this as inactive.
