### ISSUE TITLE
Display dummy cape when user has no cape

### ISSUE THREAD

**Issue by JustAlittleWolf** [tr7zw/WaveyCapes#47]
Hello I don't have a cape to display so I don't actually see what changes when changing settings on the settings screen. would be nice if the mod displayed a dummy cape (mojang cape for example) on the player when this happens so you can modify the settings and see the changes.

**Comment by tr7zw** [comment]
I mean, the effects are also not really visible during the paused settings screen(and the player is always missing when not in-game). So would that be any real help? Maaaybe something small for the future.

**Comment by JustAlittleWolf** [comment]
Hmm still really annoying.
![image](https://github.com/tr7zw/WaveyCapes/assets/54244277/ee4cfdeb-071f-4c2a-9f9d-a0e4ea7c80f4)
this screenshot might clarify what issue I am having exactly. Also noticed that when you have an elytra on it shows the elytra instead of the cape.

**Comment by tr7zw** [comment]
As I said, this preview is not really that helpful and also only there in certain cases. You can't see the different Cape Movement styles from there either, even if you have a cape.

**Comment by JustAlittleWolf** [comment]
oki convinced
