### ISSUE TITLE
Capes clip through chestplate when sneaking

### ISSUE THREAD

**Issue by Celesian** [tr7zw/WaveyCapes#5]
*Steps to Reproduce:*

1. # Wear a chest plate
2. # Switch to the third person point of view 
3. # Sneak and move around 

*Observed Results:*
The cape renders in and out as you move around. Affects leather, iron, gold, diamond, and netherite chest plates

*Expected results*
The cape doesn't clip when sneaking around 

https://imgur.com/a/BTdXkOk

Running on Minecraft 1.17.1, fabric 1.17.1 and Wavy Capes 1.0.3

**Comment by tr7zw** [comment]
Hm I guess when sneaking the cape is sliiightly too low? I'll look into it.
