### ISSUE TITLE
[Feature Request] EmoteCraft compatibility.

### ISSUE THREAD

**Issue by Amirhan-Taipovjan-Greatest-I** [tr7zw/WaveyCapes#53]
Hello!

I've noticed when some emote playing then cape with Smooth Simulation V2 with Waves wind mode settings texture goes into player body.

**Comment by tr7zw** [comment]
I have no clue what you mean. Can you provide an image or video? The cape should stay at the back of body as usual?

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
> I have no clue what you mean. Can you provide an image or video? The cape should stay at the back of body as usual?

![image](https://github.com/tr7zw/WaveyCapes/assets/51203385/0ac38250-97bf-4f45-8a88-63f53d1a97d0)

**Comment by tr7zw** [comment]
Yea there is nothing I could do about that.

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
> Yea there is nothing I could do about that.

Ok, thank You for the answer!

**Comment by tr7zw** [comment]
Same issue as the cape being able to clip into blocks instead of colliding with them. Getting this level of interaction, and then with emotecraft compatibility is just not (easily) doable and out of scope for the mod.

**Comment by tr7zw** [comment]
The only thing i want to look into at some point is making the cape physic movement compatible with playerAnimator which Emotecraft and better combat use. So that when the player leans forward in better compact or when playing an emote, that the cape reacts to that. But no clue when I'll have time for that.

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
> The only thing i want to look into at some point is making the cape physic movement compatible with playerAnimator which Emotecraft and better combat use. So that when the player leans forward in better compact or when playing an emote, that the cape reacts to that. But no clue when I'll have time for that.

Ok... but it just a nice-to-have feature.
