### ISSUE TITLE
Allow 3rd Party Downloads on CF

### ISSUE THREAD

**Issue by Boobies** [tr7zw/WaveyCapes#55]
I keep my mods up-to-date by using Ferium, which is a mod manager that can check for more recent releases of mods specified on a list on CurseForge, Modrinth, and GitHub. However, for Wavey Capes it complains that 3rd party application downloads have been disabled. I expect the same issue would be encountered by various launchers that can download mods.

This also happens with Entity Culling and probably any other mods you maintain. I'll just mention it here to avoid opening a million tickets on what is essentially the same issue.

**Comment by tr7zw** [comment]
Thats what Modrinth is for. Without going into too much detail, enabling 3rd party downloads on CF is a good way of shooting yourself into the foot, that's why I also offer all the files on Modrinth that doesn't have the same issues.
