### ISSUE TITLE
1.4.2 backport to Fabric 1.20.1

### ISSUE THREAD

**Issue by peow** [tr7zw/WaveyCapes#56]
the MoreBannerFeatures compatibility fix is huge, i tried to download and use the mod in my modpack in fabric 1.20.1 (fabric loader 0.14.22) but the game is crashing when I try to enter a world, so I'm asking for this fix to be backported to Fabric 1.20.1

crash: 
[crash-2024-01-04_21.24.06-client.txt](https://github.com/tr7zw/WaveyCapes/files/13836681/crash-2024-01-04_21.24.06-client.txt)

the crash text says that the Firstpersonmodel mod and the Elytra Physics mod are suspicious, I tried to disable them but it gave the same problem: 
[crash-2024-01-04_21.26.38-client.txt](https://github.com/tr7zw/WaveyCapes/files/13836691/crash-2024-01-04_21.26.38-client.txt)

**Comment by tr7zw** [comment]
> java.lang.NoSuchMethodError: 'net.minecraft.class_8685 net.minecraft.class_742.method_52814()'
	at dev.tr7zw.waveycapes.renderlayers.CustomCapeRenderLayer.getCapeRenderer(CustomCapeRenderLayer.java:501)
 
The crash is because the versions are not compatible with each other. 1.20.1 will get the update probably when 1.20.5 releases, and I port the project to use my new build system/pipeline which builds for 1.16.5-1.20.4 on the same codebase(like now many of my other mods).
