### ISSUE TITLE
[Bug] Capes with "Smooth" style

### ISSUE THREAD

**Issue by NoltoxGit** [tr7zw/WaveyCapes#57]
Hello,
I just noticed that when I use the "Smooth" cape style, the cape on my skin is much darker than it was originally.

Here's a video to demonstrate this :

https://github.com/tr7zw/WaveyCapes/assets/75265787/477e9e7c-fa6c-4cde-ad2f-2f5bfd7abcd9

**Comment by tr7zw** [comment]
Duplicate #14 I'm not really sure why this is the case.
