### ISSUE TITLE
STDOUT in release version

### ISSUE THREAD

**Issue by Steveplays28** [tr7zw/WaveyCapes#58]
This line seems to be printed to STDOUT every frame when the cape is updated, with Player Animator installed.

https://github.com/tr7zw/WaveyCapes/blob/1905a608932266c29b8a53cb80cd14956f192a72/src/main/java/dev/tr7zw/waveycapes/support/PlayerAnimatorSupport.java#L148

## Version info

- Minecraft `1.20.4`
- Wavey Capes `v1.4.3`

**Comment by tr7zw** [comment]
![you_wouldnt_edit_a_meme](https://github.com/tr7zw/WaveyCapes/assets/5133936/61cc0236-7562-429c-b3d5-e5498b5e8c20)
Apparently, I would. Oops.

**Comment by Steveplays28** [comment]
Thanks for the fast fix, tr7zw!

**Comment by tr7zw** [comment]
Will have to see on when I'll publish this fix. Kinda don't want to tag this as it only affects this one combination with most people probably not even noticing it. Worst case ™️ when 1.20.5 is out(or I find something else to implement/fix to make a new release reasonable).
