### ISSUE TITLE
Is possible make the cape hangs down naturally when the character crouches?

### ISSUE THREAD

**Issue by tp1415926535** [tr7zw/WaveyCapes#60]
I've noticed that when the character crouches, the cloak changes but eventually stops on a flat surface tilted at a certain angle, which still looks weird. Is it possible to make the end of the cape look like it hangs down naturally
![2024-05-16_18 54 40](https://github.com/tr7zw/WaveyCapes/assets/58326584/a68d1a93-c522-4a95-95e0-f7a96775abca)

**Comment by tr7zw** [comment]
That is in fact a bug added in the latest release. Will fix it.
