### ISSUE TITLE
Add 1.21 support

### ISSUE THREAD

**Issue by sandenbergmelo** [tr7zw/WaveyCapes#62]
It would be nice to have this mod in 1.21 version.

**Comment by tr7zw** [comment]
Not at home over the weekend, so maybe next week. Got stuck in updating the render code.

**Comment by BebroNUXXX** [comment]
> Not at home over the weekend, so maybe next week. Got stuck in updating the render code.

second week going

**Comment by tr7zw** [comment]
Correct, I was not at home both weekends. Also, people need to realize I have a full-time job, and working on the mods is a hobby in my free time.
