### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by asphyxia1337** [tr7zw/WaveyCapes#64]
Add a null check to /dev/tr7zw/waveycapes/VanillaCapeRenderer.java#Line 24 as it often causes crashes.

**Comment by tr7zw** [comment]
Mind giving an example? NMSUtil.getPlayerCape is null-checked before, so nothing in that line could be unexpectedly null, and haven't seen any crash log about this.

**Comment by asphyxia1337** [comment]
> Mind giving an example? NMSUtil.getPlayerCape is null-checked before, so nothing in that line could be unexpectedly null, and haven't seen any crash log about this.

I'll send one if I crash again.

**Comment by tr7zw** [comment]
Crash logs are saved in an extra folder, so you can just look it up there.

**Comment by tr7zw** [comment]
Oh yea, managed to somewhat reproduce this, when a skin loads async. You have to have really bad luck, but it can happen. Gonna add a quick workaround.
