### ISSUE TITLE
Cape not appearing when using MinecraftCapes on 1.16.5 forge

### ISSUE THREAD

**Issue by GamerGaven** [tr7zw/WaveyCapes#7]
the mods both work as intended independently from each other.
From the [debug.log](https://github.com/tr7zw/WaveyCapes/files/7489076/debug.log) it seems that a cape is being loaded but doesn't render in ?

**Comment by tr7zw** [comment]
There is MinecraftCapes for Forge? Well there's the issue^^ Didn't know about it, so only the Fabric version has the support in it.

**Comment by tr7zw** [comment]
Fixed
