### ISSUE TITLE
Mod doesn't seem to work with the Creeper Cape from the Minecraft Anniversary Event

### ISSUE THREAD

**Issue by Husky154** [tr7zw/WaveyCapes#74]
Cape is completely invisible. I'm on Java 1.21.
![image](https://github.com/user-attachments/assets/a48a6c09-ef54-4728-b6f5-56ff0811f4f1)

**Comment by donwnl** [comment]
Did you manage to solve it?

**Comment by tr7zw** [comment]
This has nothing to do with the cape. Its either an incompatibility with another mod, or the cape is just turned off the skin settings.

**Comment by Husky154** [comment]
It was resolved sorry meant to already mark as resolved
