### ISSUE TITLE
[Bug] Mod works on 1.21.2/1.21.3 but is stuck in loading screen

### ISSUE THREAD

**Issue by NathanL1370** [tr7zw/WaveyCapes#76]
Not sure if anyone found out about this at all. If it was, feel free to close this issue.

Menus are still interactable, just that the game is stuck in the loading screen.
https://github.com/user-attachments/assets/dd76f9ad-49fc-498d-ae54-19b5b8f24839

[latest.log](https://github.com/user-attachments/files/17652777/latest.log)

**Comment by tr7zw** [comment]
There is no 1.21.2/1.21.3 version, that's why it is not working^^. It's currently in a PR and work in progress #75
