### ISSUE TITLE
1.4.11 crash with Ears+

### ISSUE THREAD

**Issue by SplendidAlakey** [tr7zw/WaveyCapes#77]
**MC** 1.21.1
**[Ears](https://modrinth.com/mod/ears)** 1.4.6
**WaveyCapes** 1.4.11

To reproduce load into any world and use third person.
Last working version is 1.4.10.

Logs: https://gist.github.com/SplendidAlakey/ea0f01121f6ff0d519a7257615a7cb94#file-crash-log
         https://gist.github.com/SplendidAlakey/ea0f01121f6ff0d519a7257615a7cb94#file-latest-log

**Comment by tr7zw** [comment]
Thats weird, there shouldn't be any difference between 1.4.10 and 1.4.11 other than 1.21.3 support. https://github.com/tr7zw/WaveyCapes/compare/1.4.10...1.4.11#diff-2c660cc1ceff3d4e6652d6e3268e8f8a43833dda4e27d119ecd13107dd6b3b3bR23 1.21.1 has that getUUID method, yet it crashes, Will have to investigate that.
