### ISSUE TITLE
optifine cover does not appear when installing the mod

### ISSUE THREAD

**Issue by donwnl** [tr7zw/WaveyCapes#81]

**Comment by tr7zw** [comment]
In which mc version/modloader? But should be noted, that if Optifine support breaks, there are no plans anymore to add optifine support.

**Comment by donwnl** [comment]
1.21 bro

**Comment by tr7zw** [comment]
There is optifine for 1.21 o_O? I kinda assumed they stoped development finally.

**Comment by donwnl** [comment]
![7cdf4faca41a0b58](https://github.com/user-attachments/assets/504576a0-565c-4a6a-96a3-6e1952f2efa4)

**Comment by donwnl** [comment]
1.21.1, sorry

**Comment by donwnl** [comment]
![Uploading 2024-12-14_18.11.36.png…]()

**Comment by donwnl** [comment]
![Uploading 2024-12-14_18.11.36.png…]()

**Comment by donwnl** [comment]
forge e optifine 1.21.1

**Comment by donwnl** [comment]
can you solve my problem:

**Comment by tr7zw** [comment]
I'll make it short, the last time I tested optifine for anything was 1.19.4. Optifine has been entirely irrelevant for the past few years now, and there is no point in trying to fix issues with it. I didn't even know its still getting updated to new releases. Use Sodium or Vulkan mod for performance, not Optifine.

**Comment by donwnl** [comment]
But if I use those, the Optifine cover doesn't appear, right?But if I use those, the Optifine cover doesn't appear, right?

**Comment by tr7zw** [comment]
No one cares for optifine capes anymore, as you can just get a cape for free if you want via the Minecraft Capes mod. There are mods to show the capes like https://modrinth.com/mod/capes if you really want it.

**Comment by donwnl** [comment]
ok, thanks bro
